YLP-474  Implement authorization rules for seagull
mdblp/seagull pull request #25
Opened 2021-02-09 14:40 UTC by CedricPerotto

2021-02-16 06:42 UTC, ydrisR requested changes
A few questions/comments in the PR, and I'd like to discuss the changes on /users/userID

2021-02-16 06:42 UTC, ydrisR commented on lib/routes/seagullApi.js
> +        return members.concat(patients);
I don't think a HCP should be able to get the profile of other HCPs.
Same for patients, they should not be able to get profile/settings of other patients in same team

2021-02-16 06:42 UTC, ydrisR commented on lib/routes/seagullApi.js
>        var targetUserId = _.trim(req.params.userid);
how is targetUSerID used? no longer used?

2021-02-16 08:46 UTC, CedricPerotto commented on lib/routes/seagullApi.js
> +        return members.concat(patients);
HCP should be able to get first name/last name of other HCP in their teams (on order to display the list of team members in blip). 
I agree on Patients <-> Patients profiles (just thought that crew API handled that).

I rewrote this route in order to drop gatekeeper dependencies, I'm not sure about the final usage of this (and as it  strongly depends on Teams API.. I was  not so sure about teams data structure also.). 

It will need further adjustments (I'm not even sure if that route will still be directly called by blip or called through a "harbour" call).

2021-02-16 08:47 UTC, CedricPerotto commented on lib/routes/seagullApi.js
>        var targetUserId = _.trim(req.params.userid);
I think it was used for server calls... But not used anymore.

2021-02-16 10:08 UTC, CedricPerotto commented on test/testSeagullService.js
> +      sinon.stub(opaClient, 'selfAuthorized').returns(true);
selfAuthorized is the middleware used on the route tested (POST /:userid/:collection, requireCustodian middleware method).

selfAuthorized authorize server calls (and makes an inner call to serverAuthorized)

2021-02-16 10:09 UTC, CedricPerotto commented on test/testSeagullService.js
> +      sinon.stub(opaClient, 'isAuthorized').returns(true);
isAuthorized is the middleware used on the route tested (GET /:userid/:collection, requireMembership middleware method).

isAuthorized authorize server calls (and makes an inner call to serverAuthorized)

2021-02-16 10:10 UTC, CedricPerotto commented on test/testSeagullService.js
> +      sinon.stub(opaClient, 'selfAuthorized').returns(true);
selfAuthorized is the middleware used on the route tested (POST /:userid/:collection, requireCustodian middleware method).

selfAuthorized authorize server calls (and makes an inner call to serverAuthorized)

2021-02-22 07:54 UTC, ydrisR approved these changes

2021-02-22 07:56 UTC, merged