YLP-756 Bump some dependencies
mdblp/seagull pull request #33
Opened 2021-05-31 13:31 UTC by ragedblp

* Bump user-api-client to 0.5.3

2021-05-31 13:49 UTC, yvon-dblg requested changes
user-api-client still depends on older amoeba version.

2021-06-01 07:16 UTC, yvon-dblg commented on CHANGELOG.md
> +## Unreleased
```suggestion
## 0.5.4 - 2021-06-01
```

2021-06-01 07:55 UTC, yvon-dblg approved these changes
Good for me

2021-06-01 13:15 UTC, CedricPerotto approved these changes

2021-06-01 13:15 UTC, merged